path:
  ckpt_path: "./output/ckpt/VCTK"
  log_path: "./output/log/VCTK"
  result_path: "./output/result/VCTK"
optimizer:
  mask_padding: True # set model's padded outputs to padded values
  guided_attn: True # apply diagonal guided attention loss
  guided_sigma: 0.4
  guided_lambda: 1.0
  fp16_run: False
  batch_size: 64
  betas: [0.9, 0.999]
  eps: 0.00000001
  weight_decay: 0.000001
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  init_lr: 0.001
step:
  total_step: 900000
  log_step: 100
  synth_step: 500
  val_step: 1000
  save_step: 5000
